# Generated by Django 3.2.5 on 2021-07-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Особенности', 'verbose_name_plural': 'Особенности'},
        ),
    ]
